# Generated by Django 4.2.2 on 2025-03-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsos',
            name='windows_type',
            field=models.CharField(default='Windows 10', max_length=50),
            preserve_default=False,
        ),
    ]
