# Generated by Django 4.2.2 on 2025-04-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsafe', '0004_delete_windowsos_remove_resource_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('role_config', models.TextField()),
            ],
        ),
    ]
